### ISSUE TITLE
Pin this repository

### ISSUE THREAD

**Issue by RichardLitt** [remarkjs/ideas#1]
I don't have the authority to, but here: https://github.com/remarkjs. This one should show up, as should the main Remark repos. :D

**Comment by wooorm** [comment]
Definitely! It’ll look something like this! https://github.com/retextjs

**Comment by wooorm** [comment]
Hold on a sec though, updating 25 repo’s and inviting 50 people!

**Comment by RichardLitt** [comment]
What're you updating?

**Comment by wooorm** [comment]
Links, CoC, contributing docs, per plugin essentially the recent commits here: https://github.com/rehypejs/rehype-format/commits/master

And done btw, thanks!

**Comment by RichardLitt** [comment]
Want to try using build-a-space for that? :D

**Comment by wooorm** [comment]
Ha! Feel free to try that on one of the smaller plugins? I believe you’re now allowed to make those changes?!

I dunno, does it work for custom things? I wrote the docs already for the other ecosystems, they’re a bit custom?

**Comment by RichardLitt** [comment]
It should totally work for custom things - there's a custom settings.json file you can set with a link to contribute docs. Which repo should I try it on? It was made for this use case. :)
