### ISSUE TITLE
Alphabetically ordered lists (and Roman numeral)

### ISSUE THREAD

**Issue by felixakiragreen** [remarkjs/ideas#12]
### Subject of the feature

I find it quite naturally to want to write and order lists both numerically and alphabetically.

```
These items have an order:
1. First Item
2. Second Item
3. Third Item
```
or
```
These are the factors involved:
A. Large component
B. Small component
C. Unusual component
```

I think that it's also natural to want to mix these.
```
1. First Item
    a. Another Item
    b. Another Item
2. Second Item
```

I scoured the issues and documentation and this was the only related issue I could find: 
https://github.com/remarkjs/remark-lint/issues/157

I think it would be pretty straight forward with a plugin.

**Comment by wooorm** [comment]
Cool, yeah, could definitely go into a plugin!

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @felixakiragreen  !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/remarkjs/remark/discussions/categories/ideas will be the home for ideas going forward.
