### ISSUE TITLE
Embed syntax

### ISSUE THREAD

**Issue by Rokt33r** [remarkjs/ideas#14]
### Subject of the feature

I'm thinking to introduce new custom syntax for 3rd party embeddable contents like Youtube video, Twitter tweet.
The syntax describes `Embed` node which has two props, `contentType` and `identifier`. `contentType` defines what kind of content will be embedded like `twitter_tweet` and `youtube_video`. And `identifier` defines the content's id. So interface of the node should be like the below.

```ts
interface Embed <: Node {
  type: "embed"
  contentType: string
  identifier: string
}
```

And this is the syntax I'm thinking now.

```md
[$youtube_video:{video_id}] // [$youtube_video:1Pu1adxqUAg]
[$twitter_tweet:{twitter_tweet_id}] // [$twitter_tweet:12345]
```

To introduce it, I guess I need to make plugins like the below.

- `remark-embed` : Parse(and stringify) embed syntax like `remark-math`
- `rehype-embed-youtube-video` : Render `Embed` node of Youtube video
- `rehype-embed-...` : Render `Embed` node of ...

### And these are what I want to discuss now

- Is there any prior work for this?
- The syntax looks fine?(No conflicts with other plugins)
- Do we need something more?

**Comment by ChristianMurphy** [comment]
> Is there any prior work for this?

https://github.com/djm/remark-shortcodes and https://github.com/mdx-js/mdx both support embedding new content types.
shortcodes could probably be configured to support something very similar to this syntax by tuning the `startBlock` and `endBlock` options.

**Comment by Rokt33r** [comment]
https://github.com/djm/remark-shortcodes looks like the thing what I need. Thanks for the sharing! So I guess this issue can be closed for now.
