### ISSUE TITLE
Supporting pandoc fenced divs

### ISSUE THREAD

**Issue by benabel** [remarkjs/ideas#15]
### Subject of the feature

Fenced divs are some kind of generic syntax for block contents with a syntax similar to fenced code blocks but using `:` as delimiter instead of ```

Reference: https://pandoc.org/MANUAL.html#extension-fenced_divs

#### fenced divs supports attributes

```md
::::: {#special .sidebar}
Here is a paragraph.

And another.
:::::
```

pandoc converts it to `html <div>`'s:

```html
<div id="special" class="sidebar">
<p>Here is a paragraph.</p>
<p>And another.</p>
</div>
```

#### Fenced divs can be nested:

```md
::: Warning ::::::
This is a warning.

::: Danger
This is a warning within a warning.
:::
::::::::::::::::::
```

**HTML OUTPUT:**

```html
<div class="Warning">
<p>This is a warning.</p>
<div class="Danger">
<p>This is a warning within a warning.</p>
</div>
</div>
```

### Problem

I think I could adapt the code from the fenced code blocks of remark however as it is directly inside remark could you give me a plug-in that I could fork to implement it.

### Alternatives

Currently I use [`remark-custom-blocks`](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-custom-blocks#readme) but I think fenced divs is more generic and doesn't need `|` at the beginning of the line that is quite heavy.

Very similar with:

*   [`remark-container`](https://github.com/zWingz/remark-container) 
*   [`remark-containers`](https://github.com/Nevenall/remark-containers)

But I need it to be consistent with pandoc.

**Comment by wooorm** [comment]
Is this what you’re looking for? https://github.com/medfreeman/remark-generic-extensions

**Comment by benabel** [comment]
Hi @woorm, thanks for your interest. **No this is not the same**.

Actually gerenric-exetnsions is a proposal but fenced_divs are already implemented in pandoc and it works quite nicely both for md-> html or even html-> md and others(latex if you use custom filters).

**Comment by benabel** [comment]
I was looking to hack into remark-math maybe trying to modify the math block parser, but also need to implement attributes and nesting. Maybe another start point would be better?

**Comment by benabel** [comment]
I started a repository based on the code of remark-math: https://github.com/benabel/remark-fenced-divs

It is a WIP. I'll post questions in [spectrum](https://spectrum.chat/unified/remark) to finish the implementation.

**Comment by wooorm** [comment]
Awesome!

**Comment by benabel** [comment]
I published version 1.0.0 on npm https://www.npmjs.com/package/remark-fenced-divs, parsing is alright however I'd like to emit warnings if `div`s are not correctly closed how can I emit warnings in a plugin?

**Comment by ChristianMurphy** [comment]
plugins are passed a vFile, that vfile can store warning and error information https://github.com/vfile/vfile#vfilemessagereason-position-origin

**Comment by benabel** [comment]
Thank you very much for your quick answer, can you point me to a plugin that use this. I already saw messages from `math-plugin` but I don't know if they are generated by katex or by the plugin.

**Comment by ChristianMurphy** [comment]
remark-lint has many examples https://github.com/remarkjs/remark-lint/search?q=message&unscoped_q=message

**Comment by benabel** [comment]
Thank you very much, I'll investigate on this.
