### ISSUE TITLE
Support for importing React component documents by react-docgen-typescript

### ISSUE THREAD

**Issue by cytle** [remarkjs/ideas#19]
### Subject of the feature

Markdown Api documents can be generated by [`react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript). I expect to import React component documentation in markdown by react-docgen-typescript.

### Expected behavior

The Component `Column.tsx`

``` tsx
import * as React from "react";
import { Component } from "react";

/**
 * Column properties.
 */
export interface IColumnProps {
  /** prop1 description */
  prop1?: string;
  /** prop2 description */
  prop2: number;
  /**
   * prop3 description
   */
  prop3: () => void;
  /** prop4 description */
  prop4: "option1" | "option2" | "option3";
}

/**
 * Form column.
 */
export class Column extends Component<IColumnProps, {}> {
  render() {
    return <div>Test</div>;
  }
}
```

Convert the following Markdown:

``` markdown
# foo-components

## Apis

<react-docgen-typescript src="./Column.tsx" />
```

Into

``` markdown
# foo-components

## Apis

### Column

Form column.

#### props

| prop | type | default | required | description |
|---- | :----: | :-------: | :--------: | -----------|
| **prop1** | `string` | `null` | :x: | prop1 description | 
| **prop2** | `number` | `null` | :x: | prop2 description | 
| **prop3** | `() => void` | `null` | :x: | prop3 description | 
| **prop4** | `"option1" | "option2" | "option3"` | `null` | :x: | prop4 description | 
```

### Alternatives

- Use [`react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript) to parse react components

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @cytle !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/remarkjs/remark/discussions/categories/ideas will be the home for ideas going forward.
