### ISSUE TITLE
Add classes to elements by css selector

### ISSUE THREAD

**Issue by khalyomede** [remarkjs/ideas#20]
### Subject of the feature

I am creating a blog, and my articles are written in markdown. The blog uses Gridsome to convert markdown into HTML pages.

I use Tailwindcss for the UI part, and I need a way to add specific class to specific elements (bloquotes, paragraphs, ...).

### Problem

I did not found the best suited plugin to do so.

### Expected behavior

It should let us specify which class to add to which elements by their selectors, like this:

```js
{
  plugins : [
    [
      "remark-class", {
        "[p]": "mb-2 tracking-wide",
        "[h2]": "mb-4 text-gray-700 tracking-wider",
        "[bloquote]": "my-4 text-gray-500 text-right block"
      }
    ]
  ]
}
```

### Alternatives

Doing it "by hand" by adding a local code that I use as a plugin.

**Comment by ChristianMurphy** [comment]
This could be a plugin!
You can find a guide for working with syntax trees, and creating plugins here: https://unifiedjs.com/learn
Unified already has selector utilities, like: https://github.com/syntax-tree/unist-util-select which could be used to build a plugin which could be used to build this out.

> ```
> {
>   plugins : [
>     [
>       "remark-class", {
>         "[p]": "mb-2 tracking-wide",
>         "[h2]": "mb-4 text-gray-700 tracking-wider",
>         "[bloquote]": "my-4 text-gray-500 text-right block"
>       }
>     ]
>   ]
> }
> ```

With how you have this described, it wouldn't be a remark plugin, HTML are allowed in markdown, but are not a part of markdown (remark).
With how you currently have it described it references HTML tag names, which would be a rehype plugin.

If you want to make it a remark plugin, the API would refer to markdown types https://github.com/syntax-tree/mdast#nodes
If you want to make it HTML based, it can be done with rehype/hast https://github.com/syntax-tree/hast and https://github.com/syntax-tree/hast-util-select

**Comment by ChristianMurphy** [comment]
If you do go the rehype route, you may want to checkout https://github.com/martypdx/rehype-add-classes which may suit your needs

**Comment by ChristianMurphy** [comment]
https://github.com/gridsome/gridsome/issues/97#issuecomment-497909038 documents how to use rehype plugins with Gridsome
