### ISSUE TITLE
using jsx-like components from inside Markdown

### ISSUE THREAD

**Issue by fazouane-marouane** [remarkjs/ideas#4]
Hi 👋

A few months back I started fiddling with remark to get it to accept custom elements in markdown documents. In the course of doing so, I found that rehype/remark used `parser5` which was a bit constraining for it didn't accept simple things like `<MyComponent value="content" />`. So I had to write an alternative html parser that accepted jsx-like syntax for using components and marrying it with the way remark handled things.
The final code is located in https://github.com/fazouane-marouane/remark-jsx

Now that the result is quite satisfying, I was wondering if this is the kind of projects that may be hosted by `remarkjs` organisation.

Also, I'm open to any comments, feedbacks & recommendations concerning the code or the project itself. 😊

Marouane

**Comment by wooorm** [comment]
Awesome work Marouane! And yes of course, that’s a great place to put it!

You’re already a part of this org, so feel free to move it here.
Could you add me on npm too though? Two people is useful if either of us gets less active!

I also added you to [`syntax-tree`](https://github.com/syntax-tree), if you’re ever interested in creating hast/unist related things!

Finally, is there anything specific you’d like feedback on? Or just general stuff?

**Comment by fazouane-marouane** [comment]
That's great info !

I'm looking for general feedback. I'm also not sure if `smart-html-parser.js` should be moved elsewhere/extracted in an external library.

As to npm, the package name was temporary, thus the `@dumpster`. I'll remove the scope, deprecate the old one and add you as an owner on npm.

**Comment by wooorm** [comment]
Ah, totally forgot to give feedback. Sorry! Would you still like feedback?

Also: let’s move it over to remarkjs!

**Comment by fazouane-marouane** [comment]
Hello 👋
I wasn't confident that the project still interested folks, since there were some other ways popping out since then. So I moved the project here: https://github.com/remarkjs/remark-jsx

**Comment by wooorm** [comment]
I’m sure react + markdown interests folks, but I’m more sure this is the project that interests the most: you know more about the code. Is remark-jsx going to be worked on? Or should it be archived?

**Comment by fazouane-marouane** [comment]
That’s good to know! Yes I’ll continue working on it. I’ve been taken by my new job lately, but I’ll definitely come back to the project soon.

**Comment by wooorm** [comment]
Ohh that’s super understandable. Relax, take your time, and have fun at your new job! 👍

Should we close this? Or would you like to discuss other stuff?

**Comment by fazouane-marouane** [comment]
That’s fine for me now that’s published on remarkjs org. I’ll put an update once I start working on the project again 😊
