### ISSUE TITLE
Create  a `remark-lint` Jest "Runner" `jest-runner-remark`

### ISSUE THREAD

**Issue by ntwb** [remarkjs/ideas#6]
[Prettier](https://github.com/keplersj/jest-runner-prettier), [ESLint](https://github.com/jest-community/jest-runner-eslint), [flowtype](https://github.com/binygal/jest-runner-flowtype), and [stylelint](https://github.com/keplersj/jest-runner-stylelint) have Jest runners I thought it might be an interesting experiment to create a [Jest Runner](https://facebook.github.io/jest/docs/en/configuration.html#runner-string) and [projects](https://facebook.github.io/jest/docs/en/configuration.html#projects-array-string-projectconfig) config for Remark, has anyone tried creating a Jest runner for Remark?

There's a package https://github.com/rogeliog/create-jest-runner that quite a few _runners_ are already using.

**Comment by wooorm** [comment]
Sweet! I’m wondering if we could wrap the [engine](https://github.com/unifiedjs/unified-engine), like [`unified-engine-gulp`](https://github.com/unifiedjs/unified-engine-gulp) or [`unified-engine-atom`](https://github.com/unifiedjs/unified-engine-atom) as a lower level abstraction to create simpler higher level things around like [`linter-remark`](https://github.com/wooorm/linter-remark)?

**Comment by ntwb** [comment]
That sounds/looks good to my quick peek at those, and I'm honestly not too familiar on Remark (apart from our use within @stylelint) but I do know the Remark ecosystem is vast ;)

**Comment by ntwb** [comment]
I just bumped into https://www.npmjs.com/package/jest-runner-remark

Created by @keplersj at https://github.com/keplersj/jest-runner-remark

Closing this, thanks @keplersj 🙇

**Comment by keplersj** [comment]
Oh wow. I didn't even realize there was interest in a remark runner before I made it. I just prefer to run all of my unit testing, static analysis, and linting through Jest. 😆 

@ntwb Glad you found the runner!

@wooorm I do have very basic plans to refactor toward an approach using the unified engine (like the AtomLinter providers). Thankfully I have plenty of experience with Atom's linter codebases. But, are there equivalents of `remark-lint` in the rest of the unified ecosystem? Knowing about these will  help me make other Jest runners within the ecosystem.

**Comment by wooorm** [comment]
@keplersj Ah yes, basing on the engine is a good idea! I don’t know about jest internals, but you can also look at [`unified-engine-gulp`](https://github.com/unifiedjs/unified-engine-gulp) for inspiration.

There are many natural language checking [retext plugins](https://github.com/retextjs/retext/blob/master/doc/plugins.md#list-of-plugins), and in remark land the main other project is `remark-validate-links`.

Using the engine also allows presets out of the box, such as [`remark-preset-wooorm`](https://github.com/wooorm/remark-preset-wooorm)
