### ISSUE TITLE
Remark plugin idea: redact

### ISSUE THREAD

**Issue by seafoam6** [remarkjs/ideas#7]
I've been working on a plugin called "redact" (but I might not ever get it working, so throwing it in ideas to see if someone else wants to build it).

The idea is that it will blackout any text put between two tags. 

I've been rebuilding my website with Gatsby, and thought it would be cool to censor some of my writings.

Example input: 
`Yesterday we got ready for /~Joe's surprise party~/.`

Example output:
`Yesterday we got ready for █████ ████████ █████.`

my [noodling repo](https://github.com/seafoam6/remark-redact).

**Comment by RichardLitt** [comment]
@seafoam6 Did you end up making this?

**Comment by seafoam6** [comment]
@RichardLitt Yes I did. [remark-redact](https://www.npmjs.com/package/remark-redact)
