### ISSUE TITLE
oembed plugin to turn urls into embeds without special syntax

### ISSUE THREAD

**Issue by agentofuser** [remarkjs/ideas#9]
Something like:

```markdown
Here is some livecoding:

https://www.youtube.com/watch?v=q5xxyGwTxZs

Cool huh?
```

And then it becomes an iframe or whatever it needs to be.

**Comment by agentofuser** [comment]
Maybe extract it from this: https://github.com/raae/gatsby-remark-oembed

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @agentofuser  !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/remarkjs/remark/discussions/categories/ideas will be the home for ideas going forward.
